
os: Windows Server 2012

# scripts that run after cloning repository
install:
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))

build:
  publish_nuget: true # package projects with .nuspec files and push to artifacts

  # to run your custom scripts instead of automatic MSBuild
  build_script:

artifacts:
  # pushing all *.nupkg files in directory
  - path: out\*.nupkg

deploy:
  provider: NuGet
  server: http://chocolatey.org/api/v2/
  api_key:
    secure: MHXDCXK5hQWqjOXq+OHpv0P22/ZC8hblFf3aY7/8+tibY7AcziBWRtq0Zw9wIeWO
  artifact: /.*\.nupkg/
